# User data
User.create(user_name: "Ahmad Hassan", email: "a2h.ahmadhassan@gmail.com", password: "12345678", password_confirmation: "12345678", role: 2)
User.create(user_name: "M Sallah", email: "hassana2hwwe@gmail.com", password: "12345678", password_confirmation: "12345678")
User.create(user_name: "Haseeb Mustafa", email: "ahmad.naeemllah@devsinc.com", password: "12345678", password_confirmation: "12345678", role: 1)

# Seeds of posts
Post.create(title: "Hello World", body: "Dummy body text ... lorem ipsem", user_id: 2, status: 10)
Post.create(title: "Hello World", body: "Dummy body text ... lorem ipsem", user_id: 2, status: 10)
Post.create(title: "Hello World", body: "Dummy body text ... lorem ipsem", user_id: 2, status: 10)
Post.create(title: "Hello World", body: "Dummy body text ... lorem ipsem", user_id: 2, status: 10)
Post.create(title: "Hello World", body: "Dummy body text ... lorem ipsem", user_id: 2, status: 10)
Post.create(title: "Hello World", body: "Dummy body text ... lorem ipsem", user_id: 2, status: 10)
Post.create(title: "Hello World", body: "Dummy body text ... lorem ipsem", user_id: 2, status: 10)
Post.create(title: "Hello World", body: "Dummy body text ... lorem ipsem", user_id: 2, status: 10)
Post.create(title: "Hello World", body: "Dummy body text ... lorem ipsem", user_id: 2, status: 10)
Post.create(title: "Hello World", body: "Dummy body text ... lorem ipsem", user_id: 2, status: 10)
Post.create(title: "Hello World", body: "Dummy body text ... lorem ipsem", user_id: 2, status: 10)
Post.create(title: "Hello World", body: "Dummy body text ... lorem ipsem", user_id: 2, status: 10)
Post.create(title: "Hello World", body: "Dummy body text ... lorem ipsem", user_id: 2, status: 10)

Comment.create(body: "Hello World", user_id: 2, post_id: 3)
Comment.create(body: "Hello World", user_id: 2, post_id: 3)
Comment.create(body: "Hello World", user_id: 2, post_id: 3)
Comment.create(body: "Hello World", user_id: 2, post_id: 4)
Comment.create(body: "Hello World", user_id: 2, post_id: 4)
